# FROM significa que vamos começar a construção desta imagem a partir da imagem Docker já existente.
FROM alpine:3.14
# A palavra CMD mostra qua comando deverá ser utilizado ao iniciar a imagem como um container.
# CMD aceita uma lista de parâmetros como abaixo ou apenas o comando, sem declarar como lista:
# CMD echo "Hello world" funcionaria.
CMD ["echo", "Hello world! -> Pedro Vitor"]
# Agora no terminal você deve executar o comando "docker build <flags> -t <image-name> <context>"
# context sendo o caminho de pastas que o Docker se baseará para processar o Dockerfile.

#Se você executar o docker run --rm primeira-imagem o echo será feito no terminal.